### ISSUE TITLE
Postgres v12 support

### ISSUE THREAD

**Issue by dvkch** [itbm/postgresql-backup-s3#1]
Hi there,

I just found your repo through its parent's issue https://github.com/schickling/dockerfiles/issues/115. 

Do you think it would be possible to build a new version containing support for Postgresql v12 ? Your dockerfile doesn't seem to specify a specific version, I figure v12 isn't supported because it wasn't available last time you built your image.

Thanks for considering, and thanks a lot for adapting this tool after suppoort from its previous maintainer seemed to have stopped.

**Comment by itbm** [comment]
@dvkch, v12 client is now available in Alpine 3.11 so I have updated the script. Please upgrade to v1.0.3.

**Comment by yousufctec** [comment]
@itbm Can you please add support to Postgres v13?

**Comment by itbm** [comment]
Fixed in v1.0.8
